GenreTag.find_or_create_by!(name: '和食')
GenreTag.find_or_create_by!(name: '洋食')
GenreTag.find_or_create_by!(name: '中華')
GenreTag.find_or_create_by!(name: '韓国')
GenreTag.find_or_create_by!(name: '麺類')
GenreTag.find_or_create_by!(name: '丼物')
