IngredientTag.find_or_create_by!(name: '牛肉')
IngredientTag.find_or_create_by!(name: '豚肉')
IngredientTag.find_or_create_by!(name: '鶏肉')
IngredientTag.find_or_create_by!(name: '魚')
IngredientTag.find_or_create_by!(name: '野菜')
